
package com.volandoPuntoUY.model;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "UsuarioNoEsAerolineaExcepcion", targetNamespace = "http://servidor/")
public class UsuarioNoEsAerolineaExcepcion_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsuarioNoEsAerolineaExcepcion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsuarioNoEsAerolineaExcepcion_Exception(String message, UsuarioNoEsAerolineaExcepcion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public UsuarioNoEsAerolineaExcepcion_Exception(String message, UsuarioNoEsAerolineaExcepcion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.volandoPuntoUY.model.UsuarioNoEsAerolineaExcepcion
     */
    public UsuarioNoEsAerolineaExcepcion getFaultInfo() {
        return faultInfo;
    }

}
