
package com.volandoPuntoUY.model;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "VueloRepetidoException", targetNamespace = "http://servidor/")
public class VueloRepetidoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private VueloRepetidoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public VueloRepetidoException_Exception(String message, VueloRepetidoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public VueloRepetidoException_Exception(String message, VueloRepetidoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.volandoPuntoUY.model.VueloRepetidoException
     */
    public VueloRepetidoException getFaultInfo() {
        return faultInfo;
    }

}
